Map<String, String> enLang = {
  'app_name': 'Book Bus',
  'change_language': "Change Language",
  'select_language': "Select Language",
  'choose_language': "Choose your language",
  'welcome_to': "Welcome to Jaipur City Bus",
  "whats_number": "What's your mobile number",
  "give_your_number":
      "Please give us your mobile number, we will find your account or create new account",
  "firstname": "First Name",
  'enter_phone': 'Enter Phone Number',
  'phone_number': 'Mobile Number',
  "enter_first_name":"Enter First Name",
  "lastname":"Last Name",
  "enter_last_name":"Enter Last Name",
  "email":"Email",
  "enter_email_address":"Enter Email Address",
  'singin': 'Sing in',
  'continue': 'Continue',
  'whats_code': 'What\'s your code',
  'please_enter_the_code_we_are_sent_on': 'Please enter the code we are sent on',
  'to_proceed': 'to proceed',
  'create_profile': 'Create Profile',
  'upload_profile_picture': 'Upload profile picture',
  'change_profile_picture': 'Change profile picture',
  'full_name': 'Full name',
  'dob': 'Date of Birth',
  'gender': 'Gender',
  'skip_now': 'Skip Now',
  'male': 'Male',
  'female': 'Female',
  'other': 'Other',
  'select_date_of_birth': 'Select Date of Birth',
  'submit': 'Submit',
  'camera': 'Camera',
  'gallery': 'Gallery',
  'save': 'Save',
  'where_to': 'Where to?',
  'add_destination': 'Add Destination',
  'tap_to_add_destination': 'Tap to add destination',
  'view_profile': 'View Profile',
  'wallet': 'Wallet',
  'nearby_bus': 'Nearby Bus',
  'my_ticket': 'My Tickets',
  'support': 'Support',
  'terms_condition': 'Terms & Conditions',
  'privacy_policy': 'Privacy Policy',
  'logout': 'Logout',
  'logout_subtitle': 'You want to log out of this device, are you sure?',
  'yes_logout': 'Yes,Logout',
  'cancel': 'Cancel',
  'profile': 'Profile',
  'view_route': 'View Route',
  'bus_unavailable_subTitle': 'The bus stop at this location is not available. Please send a request to the available bus stops in the area.',
  'send_request' : 'Send Request',
  'available_balance': 'Available Balance',
  'withdraw': 'Withdraw',
  'add_money': 'Add Money',
  'recent_transactions': 'Recent Transactions',
  'enter_amount': 'Enter amount',
  'payment_method': 'Payment Method',
  'bank_details': 'Bank Details',
  'account_number': 'Account Number',
  'ifsc_code': 'IFSC Code',
  'enter': 'Enter',
  'send': 'Send',
  'select' : 'Select',
  'email_us' : 'Email Us',
  'write_us' : 'Write Us',
  'write_your_message' : 'Write your message',
  "invalid_phone_number": "Phone number that you entered is invalid.",
  "quota_exceeded": "Too many attempts. please try again after some time.",
  "too-many-requests":
  "We have blocked all requests from this device due to unusual activity. Try again later.",
  "user_disabled": "Phone number blocked. please contact to support.",
  "operation_not_allowed": "Operation not allowed. please contact to support.",
  "error_default": "Sorry we're facing some issues. please try after some time.",
  "network_request_failed": "No internet connection.",
  "invalid_verification_code": "You entered incorrect OTP.",
  'live_status' : 'Live Status',
  'view_ticket' : 'View Ticket',
  'emergency' : 'Emergency',
  'tourist_area' : 'Tourist Area',
  'add_contact' : 'Add Contact',
  'call' : 'CALL',
  'historical_attraction' : 'Historical Attractions',
  'bus_unavailable_title' : 'Bus stop is unavailable at this location',
  'bus_unavailable_subtitle' : 'This location will be served by a bus stop in the near future. Please tap here to send a request.',
  'view_bus' : 'View Bus',
  'your_location' : 'Your Location',
  'book_ticket' : 'Book Ticket',
  'rewards' : 'Rewards',
  'view_bus_route' : 'View Bus Route',
  'settings' : 'Settings',
  'my_voucher' : 'My Voucher',
  'cashback_won' : 'Cashback Won',
  'my_rewards' : 'My Rewards',
  'you_won_reward' : "Yay! You've won a Scratch Card",
  'scratch_now' : "Scratch Now",
  'mobile_number' : "Mobile Number",
  'change' : "Change",
  'number_exist' : "This phone number is already in use with another account.",
  'otp_sent' : "Otp is sent to your mobile number.",
  'journey_start' : "Journey Start",
  'journey_end' : "Journey End",
  'ticket_id' : "Ticket ID",
  'date_time' : "Date & Time",
  'ticket_amount' : "Ticket Amount",
  'passenger' : "Passenger",
  'book_ticket_note' : "You can book upto",
  'ticket' : "Ticket",
  'pay_via' : "Pay via",
  'person' : "Person"
};
